services:
  bot:
    container_name: d1pq-bot
    image: $IMAGE_NAME
    env_file:
      - .env
      - database.env
      - redis.env
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ./bot
          target: /bot
    ports:
      - 8000:8000