

STICKERS = {
    'AgADDAAD1XH9MQ': ('b', 0),
    'AgADEAAD1XH9MQ': ('b', 1),
    'AgADFAAD1XH9MQ': ('b', 2),
    'AgADGAAD1XH9MQ': ('b', 3),
    'AgADHAAD1XH9MQ': ('b', 4),
    'AgADIAAD1XH9MQ': ('b', 5),
    'AgADJAAD1XH9MQ': ('b', 6),
    'AgADKAAD1XH9MQ': ('b', 7),
    'AgADLAAD1XH9MQ': ('b', 8),
    'AgADMAAD1XH9MQ': ('b', 9),
    'AgADNAAD1XH9MQ': ('b', 'draw', 2),
    'AgADBgAD1XH9MQ': ('b', 'skip'),
    'AgADAgAD1XH9MQ': ('b', 'reverse'),
    'AgADDQAD1XH9MQ': ('g', 0),
    'AgADEQAD1XH9MQ': ('g', 1),
    'AgADFQAD1XH9MQ': ('g', 2),
    'AgADGQAD1XH9MQ': ('g', 3),
    'AgADHQAD1XH9MQ': ('g', 4),
    'AgADIQAD1XH9MQ': ('g', 5),
    'AgADJQAD1XH9MQ': ('g', 6),
    'AgADKQAD1XH9MQ': ('g', 7),
    'AgADLQAD1XH9MQ': ('g', 8),
    'AgADMQAD1XH9MQ': ('g', 9),
    'AgADNQAD1XH9MQ': ('g', 'draw', 2),
    'AgADBwAD1XH9MQ': ('g', 'skip'),
    'AgADAwAD1XH9MQ': ('g', 'reverse'),
    'AgADDgAD1XH9MQ': ('r', 0),
    'AgADEgAD1XH9MQ': ('r', 1),
    'AgADFgAD1XH9MQ': ('r', 2),
    'AgADGgAD1XH9MQ': ('r', 3),
    'AgADHgAD1XH9MQ': ('r', 4),
    'AgADIgAD1XH9MQ': ('r', 5),
    'AgADJgAD1XH9MQ': ('r', 6),
    'AgADKgAD1XH9MQ': ('r', 7),
    'AgADLgAD1XH9MQ': ('r', 8),
    'AgADMgAD1XH9MQ': ('r', 9),
    'AgADNgAD1XH9MQ': ('r', 'draw', 2),
    'AgADCAAD1XH9MQ': ('r', 'skip'),
    'AgADBAAD1XH9MQ': ('r', 'reverse'),
    'AgADDwAD1XH9MQ': ('y', 0),
    'AgADEwAD1XH9MQ': ('y', 1),
    'AgADFwAD1XH9MQ': ('y', 2),
    'AgADGwAD1XH9MQ': ('y', 3),
    'AgADHwAD1XH9MQ': ('y', 4),
    'AgADIwAD1XH9MQ': ('y', 5),
    'AgADJwAD1XH9MQ': ('y', 6),
    'AgADKwAD1XH9MQ': ('y', 7),
    'AgADLwAD1XH9MQ': ('y', 8),
    'AgADMwAD1XH9MQ': ('y', 9),
    'AgADNwAD1XH9MQ': ('y', 'draw', 2),
    'AgADCQAD1XH9MQ': ('y', 'skip'),
    'AgADBQAD1XH9MQ': ('y', 'reverse'),
    'AgADCwAD1XH9MQ': ('bonus', 'draw', 4),
    'AgADCgAD1XH9MQ': ('bonus', 'choose'),
}
